require "default.options"
require "default.keymaps"
require "default.plugins"
require "default.optbckr"
require "default.cmpltns"
require "default.lsp"
require "default.telescp"
require "default.treestr"
require "default.autpirs"
require "default.comment"
require "default.gitsign"
require "default.nvimtre"
require "default.bufline"
require "default.lualine"
require "default.tglterm"
require "default.indntln"
require "default.impatnt"
require "default.colours" -- since the bufline acts strange, I'll recall the colours here.
